<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kOBry.V' shared service.

return $this->privates['.service_locator.kOBry.V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BienController::deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController::deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController::indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController::updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\UserSecurityController::login' => ['privates', '.service_locator.FAee79i', 'get_ServiceLocator_FAee79iService.php', true],
    'App\\Controller\\BienController:deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController:deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController:indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\BienController:updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\UserSecurityController:login' => ['privates', '.service_locator.FAee79i', 'get_ServiceLocator_FAee79iService.php', true],
], [
    'App\\Controller\\BienController::deleteVerif' => '?',
    'App\\Controller\\BienController::deleterArticle' => '?',
    'App\\Controller\\BienController::indexAction' => '?',
    'App\\Controller\\BienController::updateAction' => '?',
    'App\\Controller\\UserSecurityController::login' => '?',
    'App\\Controller\\BienController:deleteVerif' => '?',
    'App\\Controller\\BienController:deleterArticle' => '?',
    'App\\Controller\\BienController:indexAction' => '?',
    'App\\Controller\\BienController:updateAction' => '?',
    'App\\Controller\\UserSecurityController:login' => '?',
]);
