<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.VpK.6BC.Symfony\Component\HttpFoundation\Session\Session' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/Session/SessionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/Session/Session.php';

return $this->privates['.errored..service_locator.VpK.6BC.Symfony\\Component\\HttpFoundation\\Session\\Session'] = new \Symfony\Component\HttpFoundation\Session\Session();
