<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VpK.6BC' shared service.

return $this->privates['.service_locator.VpK.6BC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'session' => ['privates', '.errored..service_locator.VpK.6BC.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.VpK.6BC": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists. Try changing the type-hint to "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface" instead.'],
], [
    'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
]);
