<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqO4JYz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqO4JYz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqO4JYz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqO4JYz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXqO4JYz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XqO4JYz',
    'container.build_id' => '781462dc',
    'container.build_time' => 1571060706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqO4JYz');
