<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFAkSnG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFAkSnG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMFAkSnG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMFAkSnG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMFAkSnG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MFAkSnG',
    'container.build_id' => 'ac3c26de',
    'container.build_time' => 1570443785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMFAkSnG');
